[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = [
  "apps/users-service/**",
  "libs/shared/**",
  "nx.json",
  "package.json",
  "tsconfig*.json"
]

[deploy]
healthcheckPath = ""
restartPolicyType = "never"
