[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
buildCommand = "--build-arg SERVICE_NAME=auth-service"
watchPatterns = [
  "apps/auth-service/**",
  "libs/shared/**",
  "nx.json",
  "package.json",
  "tsconfig*.json"
]

[deploy]
healthcheckPath = "/api/auth/health"
restartPolicyType = "never"
